baseURL = "https://felipemxg.github.io/"
languageCode = "en-us"
title = "Felipe Marx Digital Garden"
theme = "hugo-digital-garden-theme"
themesdir = "themes"
copyright = "Theme by Nigalya Ponya | Felipe Marx ©"


[params]
  name = "Felipe Marx"
  description = "Software Engineer who likes to meditate."
  initials = "FM"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/felipemxg/"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/felipemxg/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
